include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_put_control_body_on_new_line
    - always_declare_return_types
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_function_literals_in_foreach_calls
    - directives_ordering
    - omit_local_variable_types
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_collection_literals
    - prefer_equal_for_default_values
    - sized_box_for_whitespace
    - sort_child_properties_last
    - eol_at_end_of_file
    - comment_references
    - sort_pub_dependencies
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_lambdas
    - use_named_constants
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_annotation_target: ignore
    missing_required_param: warning
    missing_return: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"